"""add inspection id to certificates

Revision ID: 306b8b9dc0eb
Revises: 292175cb1335
Create Date: 2026-09-26 23:16:11.051879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306b8b9dc0eb'
down_revision: Union[str, Sequence[str], None] = '292175cb1335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('inspection_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'certificates', 'inspections', ['inspection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_column('certificates', 'inspection_id')
    # ### end Alembic commands ###
