"""add created_at to batteries

Revision ID: 37a6729a5ce0
Revises: c8dbd7e28846
Create Date: 2026-09-24 19:23:05.855981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a6729a5ce0'
down_revision: Union[str, Sequence[str], None] = 'c8dbd7e28846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batteries', 'created_at')
    # ### end Alembic commands ###
