"""add health_status to inspections

Revision ID: 5d22f6fd621d
Revises: 6f3eefddd71e
Create Date: 2026-09-02 21:47:49.609693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d22f6fd621d'
down_revision: Union[str, Sequence[str], None] = '6f3eefddd71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as nullable
    op.add_column(
        "inspections",
        sa.Column("health_status", sa.String(length=20), nullable=True),
    )

    # Step 2: Populate existing rows
    op.execute(
        """
        UPDATE inspections
        SET health_status =
            CASE
                WHEN health_score >= 90 THEN 'Excellent'
                WHEN health_score >= 75 THEN 'Good'
                WHEN health_score >= 60 THEN 'Warning'
                ELSE 'Critical'
            END
        """
    )

    # Step 3: Make column NOT NULL
    op.alter_column(
        "inspections",
        "health_status",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'health_status')
    # ### end Alembic commands ###
