"""add battery warranty lifecycle

Revision ID: c8dbd7e28846
Revises: 4ec475d75a86
Create Date: 2026-09-21 19:57:06.807825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8dbd7e28846'
down_revision: Union[str, Sequence[str], None] = '4ec475d75a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # Nullable columns
    op.add_column(
        "batteries",
        sa.Column("purchase_date", sa.Date(), nullable=True),
    )

    op.add_column(
        "batteries",
        sa.Column("warranty_start_date", sa.Date(), nullable=True),
    )

    op.add_column(
        "batteries",
        sa.Column("warranty_end_date", sa.Date(), nullable=True),
    )

    op.add_column(
        "batteries",
        sa.Column("retired_date", sa.Date(), nullable=True),
    )

    op.add_column(
        "batteries",
        sa.Column("retirement_reason", sa.String(length=255), nullable=True),
    )

    # Step 1: Add lifecycle_status with a temporary server default
    op.add_column(
        "batteries",
        sa.Column(
            "lifecycle_status",
            sa.String(length=20),
            nullable=False,
            server_default="Active",
        ),
    )

    # Step 2: Remove server default
    op.alter_column(
        "batteries",
        "lifecycle_status",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batteries', 'retirement_reason')
    op.drop_column('batteries', 'retired_date')
    op.drop_column('batteries', 'lifecycle_status')
    op.drop_column('batteries', 'warranty_end_date')
    op.drop_column('batteries', 'warranty_start_date')
    op.drop_column('batteries', 'purchase_date')
    # ### end Alembic commands ###
