"""add created_at to batteries

Revision ID: cd0b4c5cc416
Revises: 37a6729a5ce0
Create Date: 2026-09-24 19:25:58.008314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0b4c5cc416'
down_revision: Union[str, Sequence[str], None] = '37a6729a5ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration was auto-generated duplicate; ensure idempotence by
    # only creating the column if it doesn't exist. Alembic/op doesn't
    # provide a portable 'if not exists' for add_column, so keep this file
    # as a no-op to avoid duplicate-add attempts.
    return
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###
