"""add digital battery passport fields

Revision ID: f73e3955403c
Revises: eb60beb118e5
Create Date: 2026-08-17 19:15:25.986162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73e3955403c'
down_revision: Union[str, Sequence[str], None] = 'eb60beb118e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'batteries',
        sa.Column(
            'model',
            sa.String(length=100),
            nullable=False,
            server_default='Unknown'
        )
    )

    op.add_column(
        'batteries',
        sa.Column(
            'chemistry',
            sa.String(length=50),
            nullable=False,
            server_default='Unknown'
        )
    )

    op.add_column(
        'batteries',
        sa.Column(
            'capacity',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'batteries',
        sa.Column(
            'voltage',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'batteries',
        sa.Column(
            'manufacturing_date',
            sa.Date(),
            nullable=False,
            server_default=sa.text("'2026-01-01'")
        )
    )

    op.add_column(
        'batteries',
        sa.Column(
            'installation_date',
            sa.Date(),
            nullable=True
        )
    )

    op.create_index(
        op.f('ix_batteries_id'),
        'batteries',
        ['id'],
        unique=False
    )

    # Remove temporary defaults after existing rows are populated.
    op.alter_column(
        'batteries',
        'model',
        server_default=None
    )

    op.alter_column(
        'batteries',
        'chemistry',
        server_default=None
    )

    op.alter_column(
        'batteries',
        'capacity',
        server_default=None
    )

    op.alter_column(
        'batteries',
        'voltage',
        server_default=None
    )

    op.alter_column(
        'batteries',
        'manufacturing_date',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batteries_id'), table_name='batteries')
    op.drop_column('batteries', 'installation_date')
    op.drop_column('batteries', 'manufacturing_date')
    op.drop_column('batteries', 'voltage')
    op.drop_column('batteries', 'capacity')
    op.drop_column('batteries', 'chemistry')
    op.drop_column('batteries', 'model')
    # ### end Alembic commands ###
